### ISSUE TITLE
Error message that geometry is unavailable for years prior to 2010 needed

### ISSUE THREAD

**Issue by gustavonovoa** [christopherkenny/geomander#11]
If you the run the following, for example:

`create_block_table(state="TX", county="Tarrant" , year=2000, geometry=TRUE)`

You get this error:

Error in `.data$GEOID`:
! Column `GEOID` not found in `.data`.
Run `rlang::last_trace()` to see where the error occurred.

Should return an error that geometry is not available for 2000 or have the documentation say that geometry is only available for 2010/2020.

**Comment by christopherkenny** [comment]
Hello @gustavonovoa. This was actually an issue within `censable`, that `geomander` uses for gathering Census API data. It's now fixed on GitHub in censable version 0.0.5, which can be installed with `remotes::install_github('christopherkenny/censable')`. I will get that updated on CRAN in the near future. Sorry for the trouble.

**Comment by gustavonovoa** [comment]
No trouble. Thanks for creating and updating the package.
