### ISSUE TITLE
Select not applicable in create_block_table

### ISSUE THREAD

**Issue by AnkitPatel-21** [christopherkenny/geomander#7]
Running create_block_table(state="TX", county="Harris") causes the following error, which seems to stem from the call to tidycensus potentially not returning a data frame? Running on provided data sets also does not work.
Error in UseMethod("select") : 
  no applicable method for 'select' applied to an object of class "character"

**Comment by christopherkenny** [comment]
Yeah, so that error usually indicates that `tidycensus` was unable to match the call. It looks like, in this instance, you can supply the full county name as follows and it will work:
```
create_block_table('TX', 'Harris County')
```

Normally, you can just give the name of the county (`'Harris'`) without adding `' County'`, so not sure what happened there.

**Comment by AnkitPatel-21** [comment]
Thanks for the input! I ran the function again with this call but the same result occurred, which I take to mean that there are no entries in the tidycensus decennial data that match (which shouldn't be true). Do you have any other ideas as to what might be the issue, because it is occurring regardless of which parameters are set ("NY" and "Rockland", "CA" and "Orange", etc.). Thanks again!

**Comment by AnkitPatel-21** [comment]
Thanks! I tried running that command but the same result pops up, both for Harris county in texas, as well as Rockland county in NY, which seems to be an oft-used example. I also tried running it on my friends computer in case something is wrong with my Rstudio environment but no luck there.
  

  
I appreciate any answer you may have!
  
  
  
  
  
  
  

  
  
>

**Comment by christopherkenny** [comment]
Do you have the most updated version of `tidycensus`? For each other those, I can get outputs without including the "County" ending. For example:
```
 test <- geomander::create_block_table(state = 'CA', county = 'Orange')
 ```
 runs without a problem.
