### ISSUE TITLE
upcoming sf breaks geomander on CRAN

### ISSUE THREAD

**Issue by edzer** [christopherkenny/geomander#9]
See https://win-builder.r-project.org/incoming_pretest/sf_1.0-7_20220305_170150/reverseDependencies/changes.txt

Please refrain from testing exact equality of objects returned against saved versions, as it prohibits developers to add attributes to objects (here, of class `sgbp`) whose functionality is simply extended, not changed.

**Comment by christopherkenny** [comment]
Hello @edzer. Sorry about that. Removed the exact equality check and will get a patch submitted to CRAN by end of day.

**Comment by edzer** [comment]
Great, thanks!
